# alert_service.py - Sends alerts via Gmail SMTP (email) and Playwright WhatsApp
import logging
import smtplib
import asyncio
import urllib.parse
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from playwright.async_api import async_playwright
from app.config import settings

logger = logging.getLogger(__name__)


def format_whatsapp_alert(alert_type: str, patient_name: str, patient_id: str,
                          detail: str, action: str) -> str:
    """Generate a highly detailed, extremely professional, and modern clinical notification for WhatsApp."""
    now = datetime.now().strftime("%d %b %Y at %I:%M %p")

    theme_map = {
        "CRITICAL": {
            "header_emoji": "🚨🔴🚨",
            "banner": "⚡ *CRITICAL LIFE-SAFETY ALERT* ⚡",
            "severity_tag": "🔥 *CRITICAL (IMMEDIATE ACTION REQUIRED)*",
            "badge": "🔴 High Urgency"
        },
        "WARNING": {
            "header_emoji": "⚠️🟡⚠️",
            "banner": "⚠️ *CLINICAL WARNING ALERT* ⚠️",
            "severity_tag": "🟡 *WARNING (PROMPT ATTENTION REQUIRED)*",
            "badge": "🟡 Medium Urgency"
        },
        "INFO": {
            "header_emoji": "ℹ️🔵ℹ️",
            "banner": "ℹ️ *CLINICAL ADVISORY* ℹ️",
            "severity_tag": "🔵 *INFORMATION ALERT*",
            "badge": "🔵 Routine Urgency"
        }
    }
    
    theme = theme_map.get(alert_type.upper(), {
        "header_emoji": "🔔⚪🔔",
        "banner": "🔔 *SYSTEM NOTIFICATION* 🔔",
        "severity_tag": "⚪ *STANDARD SYSTEM ALERT*",
        "badge": "⚪ Standard Urgency"
    })

    # Clean detail lines with custom indent and medical icons
    detail_lines = ""
    for line in detail.strip().split("\n"):
        if line.strip():
            detail_lines += f"\n   🩺 _{line.strip()}_"

    # Clean action lines with styled bold checkboxes
    action_lines = ""
    for i, line in enumerate(action.strip().split("\n")):
        if line.strip():
            action_lines += f"\n   *[{i+1}]* ✅ {line.strip()}"

    message = (
        f"{theme['header_emoji']} {theme['banner']} {theme['header_emoji']}\n"
        f"🏥 *REHABAI COMPANION CLINICAL INTELLIGENCE PLATFORM*\n"
        f"────────────────────────────────\n"
        f"\n"
        f"👤 *PATIENT TRIAGE PROFILE:*\n"
        f"   • *Full Name:*  _{patient_name}_\n"
        f"   • *Unique ID:*  ``` {patient_id} ```\n"
        f"   • *Assessment Severity:* {theme['badge']}\n"
        f"   • *Registered Timestamp:*  📅 _{now}_\n"
        f"\n"
        f"📊 *DIAGNOSTIC TELEMETRY & SYMPTOMS:*\n"
        f"   *Status Indicators:* {theme['severity_tag']}\n"
        f"{detail_lines}\n"
        f"\n"
        f"🛡️ *IMMEDIATE CLINICAL INTERVENTION PROTOCOL:*\n"
        f"   _Please execute the following medical guidelines immediately to prevent clinical setbacks:_\n"
        f"{action_lines}\n"
        f"\n"
        f"────────────────────────────────\n"
        f"🧑‍⚕️ *PHYSICIAN DIRECTIVE & MITIGATION STEPS:*\n"
        f"   1️⃣ Contact the patient's primary emergency contact immediately.\n"
        f"   2️⃣ Update patient's clinical chart inside the physician portal.\n"
        f"   3️⃣ Coordinate with the rehabilitation clinic on-call team for possible immediate session adjustment.\n"
        f"\n"
        f"🔒 *SYSTEM DATA INTEGRITY NOTICE:*\n"
        f"   _This is an automated encrypted transmission generated by the RehabAI Clinical Intelligence Platform. Patient data is handled in compliance with global clinical standards._\n"
        f"\n"
        f"🤖 *RehabAI Platform Assistant System v2.0*"
    )
    return message


def format_email_alert(alert_type: str, patient_name: str, patient_id: str,
                       detail: str, action: str) -> str:
    """Generate a richly formatted, premium HTML email alert message."""
    now = datetime.now().strftime("%d %b %Y, %I:%M %p")
    
    # Premium color and emoji mappings
    theme_map = {
        "CRITICAL": {
            "primary": "#ef4444",   # Vibrant Red
            "bg_light": "#fef2f2",  # Soft Red
            "emoji": "🚨",
            "title": "CRITICAL MEDICAL ALERT"
        },
        "WARNING": {
            "primary": "#f59e0b",   # Amber Orange
            "bg_light": "#fffbeb",  # Soft Orange
            "emoji": "⚠️",
            "title": "CLINICAL WARNING ALERT"
        },
        "INFO": {
            "primary": "#3b82f6",   # Royal Blue
            "bg_light": "#eff6ff",  # Soft Blue
            "emoji": "ℹ️",
            "title": "CLINICAL INFORMATION ALERT"
        }
    }
    
    theme = theme_map.get(alert_type.upper(), {
        "primary": "#6b7280",
        "bg_light": "#f9fafb",
        "emoji": "🔔",
        "title": "SYSTEM ALERT"
    })
    
    # Format details and actions into structured HTML lists with premium styling
    detail_lines = "".join(f"<li style='margin-bottom: 8px; line-height: 1.5;'>{line}</li>" for line in detail.strip().split("\n") if line.strip())
    action_lines = "".join(f"<li style='margin-bottom: 8px; line-height: 1.5;'>{line}</li>" for line in action.strip().split("\n") if line.strip())

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>RehabAI Clinical Alert</title>
    </head>
    <body style="margin: 0; padding: 0; background-color: #f1f5f9; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale;">
        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="background-color: #f1f5f9; padding: 40px 10px;">
            <tr>
                <td align="center">
                    <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px; background-color: #ffffff; border-radius: 16px; box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.05); overflow: hidden;">
                        
                        <!-- Header Banner -->
                        <tr>
                            <td style="background-color: #0f172a; padding: 30px 40px; text-align: center;">
                                <div style="display: inline-block; font-size: 13px; font-weight: 700; color: #38bdf8; letter-spacing: 0.15em; margin-bottom: 8px; text-transform: uppercase;">
                                    🤖 REHABAI COMPANION PLATFORM
                                </div>
                                <h1 style="margin: 0; color: #ffffff; font-size: 24px; font-weight: 800; letter-spacing: -0.025em;">
                                    {theme["emoji"]} {theme["title"]}
                                </h1>
                            </td>
                        </tr>
                        
                        <!-- Status Alert Banner -->
                        <tr>
                            <td style="background-color: {theme["bg_light"]}; border-bottom: 1px solid #e2e8f0; padding: 20px 40px; text-align: center;">
                                <span style="background-color: {theme["primary"]}; color: #ffffff; font-size: 12px; font-weight: 800; padding: 6px 16px; border-radius: 9999px; text-transform: uppercase; letter-spacing: 0.05em; display: inline-block;">
                                    Status: {alert_type.upper()}
                                </span>
                            </td>
                        </tr>
                        
                        <!-- Patient Info Card -->
                        <tr>
                            <td style="padding: 40px 40px 20px 40px;">
                                <h2 style="margin: 0 0 16px 0; font-size: 18px; font-weight: 700; color: #1e293b; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px;">
                                    👤 Patient Profile Details
                                </h2>
                                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="font-size: 15px;">
                                    <tr>
                                        <td style="padding: 8px 0; color: #64748b; width: 120px;"><strong>Patient Name:</strong></td>
                                        <td style="padding: 8px 0; color: #0f172a; font-weight: 600;">{patient_name}</td>
                                    </tr>
                                    <tr>
                                        <td style="padding: 8px 0; color: #64748b;"><strong>Patient ID:</strong></td>
                                        <td style="padding: 8px 0; color: #0f172a; font-weight: 600; font-family: monospace; font-size: 14px;">🆔 {patient_id}</td>
                                    </tr>
                                    <tr>
                                        <td style="padding: 8px 0; color: #64748b;"><strong>Timestamp:</strong></td>
                                        <td style="padding: 8px 0; color: #0f172a; font-weight: 500;">📅 {now}</td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                        
                        <!-- Clinical Details -->
                        <tr>
                            <td style="padding: 0 40px 20px 40px;">
                                <div style="background-color: #f8fafc; border-left: 4px solid {theme["primary"]}; border-radius: 0 8px 8px 0; padding: 24px;">
                                    <h3 style="margin: 0 0 12px 0; font-size: 16px; font-weight: 700; color: {theme["primary"]};">
                                        📋 Clinical Details & Thresholds
                                    </h3>
                                    <ul style="margin: 0; padding-left: 20px; color: #334155; font-size: 15px;">
                                        {detail_lines}
                                    </ul>
                                </div>
                            </td>
                        </tr>
                        
                        <!-- Actions Required -->
                        <tr>
                            <td style="padding: 0 40px 30px 40px;">
                                <div style="background-color: #f8fafc; border-left: 4px solid #0f172a; border-radius: 0 8px 8px 0; padding: 24px;">
                                    <h3 style="margin: 0 0 12px 0; font-size: 16px; font-weight: 700; color: #0f172a;">
                                        ⚡ Recommended Action Plan
                                    </h3>
                                    <ol style="margin: 0; padding-left: 20px; color: #334155; font-size: 15px;">
                                        {action_lines}
                                    </ol>
                                </div>
                            </td>
                        </tr>
                        
                        <!-- Footer Section -->
                        <tr>
                            <td style="background-color: #f8fafc; border-top: 1px solid #e2e8f0; padding: 30px 40px; text-align: center;">
                                <p style="margin: 0 0 8px 0; font-size: 12px; font-weight: 600; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em;">
                                    🏥 RehabAI Clinical Assistant System
                                </p>
                                <p style="margin: 0; font-size: 12px; color: #94a3b8; line-height: 1.5;">
                                    This is an automated clinical notification. Please do not reply directly to this email.<br>
                                    To manage your alert preferences, please log into your physician dashboard.
                                </p>
                            </td>
                        </tr>
                        
                    </table>
                </td>
            </tr>
        </table>
    </body>
    </html>
    """
    return html
async def send_email_alert(to_email: str, subject: str, body: str) -> bool:
    """Send email alert via Gmail SMTP — no SendGrid needed."""
    try:
        msg = MIMEMultipart()
        msg['From']    = settings.GMAIL_SENDER_EMAIL
        msg['To']      = to_email
        msg['Subject'] = subject
        
        # Detect if body is HTML
        if "<html>" in body.lower() or "<body" in body.lower() or "<div" in body.lower():
            msg.attach(MIMEText(body, 'html'))
        else:
            msg.attach(MIMEText(body, 'plain'))

        # Connect to Gmail SMTP server
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(settings.GMAIL_SENDER_EMAIL, settings.GMAIL_APP_PASSWORD)
            server.sendmail(settings.GMAIL_SENDER_EMAIL, to_email, msg.as_string())

        logger.info(f"✅ Email sent to {to_email} | Subject: {subject}")
        return True
    except Exception as e:
        logger.error(f"❌ Failed to send email to {to_email}: {e}", exc_info=True)
        return False


async def send_whatsapp_alert(phone_number: str, message: str) -> bool:
    """Send WhatsApp message by running an isolated worker process to bypass Windows asyncio/subprocess limitations."""
    try:
        import subprocess
        import sys
        import os

        logger.info(f"Spawning isolated WhatsApp worker for {phone_number}...")

        # Build path to whatsapp_worker.py
        current_dir = os.path.dirname(os.path.abspath(__file__))
        worker_path = os.path.join(current_dir, "whatsapp_worker.py")

        # Run worker as a clean subprocess to completely isolate the event loop
        # This completely resolves the Windows ProactorEventLoop/NotImplementedError conflicts!
        process = subprocess.Popen(
            [sys.executable, worker_path, "--phone", phone_number, "--message", message],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )

        # Wait for the worker to finish in a non-blocking thread pool
        loop = asyncio.get_event_loop()
        stdout, stderr = await loop.run_in_executor(None, process.communicate)

        if process.returncode == 0 and "SUCCESS" in stdout:
            logger.info(f"✅ WhatsApp sent successfully via isolated worker process!")
            return True
        else:
            logger.error(f"❌ WhatsApp worker failed: {stdout}\n{stderr}")
            return False

    except Exception as e:
        logger.error(f"❌ Failed to send WhatsApp to {phone_number} via worker: {e}", exc_info=True)
        return False


async def send_alert(channel: str, recipient: str, subject: str, message: str) -> bool:
    """Unified alert sender — routes to email or WhatsApp based on channel."""
    if channel == "email":
        return await send_email_alert(to_email=recipient, subject=subject, body=message)
    elif channel == "whatsapp":
        return await send_whatsapp_alert(phone_number=recipient, message=message)
    else:
        logger.warning(f"Unknown alert channel: {channel}")
        return False
