"""Add exercise_plans model

Revision ID: cac868d19d6f
Revises: ce76ffdb6d84
Create Date: 2026-05-17 12:45:57.132671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cac868d19d6f'
down_revision: Union[str, None] = 'ce76ffdb6d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('generated_date', sa.Date(), nullable=False),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('exercises', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('setback_probability', sa.Float(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_plans')
    # ### end Alembic commands ###
